name: Create s3 Static Site

on:
  issues:
    types: [opened]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Extract Bucket Name from Issue
        run: |
          export BUCKET_NAME=$(echo "${{ github.event.issue.title }}")
          echo "Bucket Name: $BUCKET_NAME"
          echo "BUCKET_NAME=$BUCKET_NAME" >> $GITHUB_ENV

      - name: Run Terraform
        run: |
          cd terraform
          cd s3-bucket-static
          terraform init
          terraform apply -auto-approve -var="bucket_name=${{ env.BUCKET_NAME }}"

      - name: Add comment
        uses: actions/gh-script@v2
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            gh issue comment "$NUMBER" --repo "$REPO" --body "O bucket s3 foi criado com sucesso!"
        env:
          NUMBER: ${{ github.event.issue.number }}
          REPO: ${{ github.repository }}
